### ISSUE TITLE
Opprette dev branch

### ISSUE THREAD

**Issue by sharizard** [andreasmolund/reca#2]
Ikke jobb direkte i master branchen, men i en dev branch eller feature branch. Merge inn til master når dev er 100% stabil. Små oppgaver bør gjøres på feature branches som du oppretter utifra dev. Så fort feature branch er stabil, merge til dev. Når dev har fått en god del endringer og er stabil, merge inn til master.

Master <- Dev <- [Liste av feature branches]

**Comment by andreasmolund** [comment]
Ja, den flyten er oblig i team og i jobb. Men jeg jobber alene her, så så en master-branch med noen andre små branches funker bra for meg. Eller jo, ja, samtidig kunne det jo være en idé, hvis noen vil forke repoet f.eks. Master bør jo være kjøreklar.
